#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pssh
Version  : 1.0.0b2
Release  : 12
URL      : https://github.com/ParallelSSH/parallel-ssh/archive/1.0.0b2.tar.gz
Source0  : https://github.com/ParallelSSH/parallel-ssh/archive/1.0.0b2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: pssh-python
Requires: paramiko
BuildRequires : paramiko
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
============
parallel-ssh
============
Asynchronous parallel SSH client library.

%package python
Summary: python components for the pssh package.
Group: Default

%description python
python components for the pssh package.


%prep
%setup -q -n parallel-ssh-1.0.0b2

%build
export LANG=C
export SOURCE_DATE_EPOCH=1487895389
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1487895389
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
